
[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
bitflags = "0.4"
libc = "0.2"
gio-sys = "0.3.1"
glib-sys = "0.3.1"

[features]

[lib]
name = "secret_sys"

[package]
build = "build.rs"
links = "secret"
name = "secret-sys"
version = "0.2.0"
